# -*- coding: utf-8 -*-
"""LLM_as_Judge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1itqP9jtLL1Zao6-4XMu0DRH2Ot9HF1Hg
"""

import pandas as pd

import json
import urllib.request

url = "https://huggingface.co/datasets/tatsu-lab/alpaca_eval/resolve/main/alpaca_eval.json"
with urllib.request.urlopen(url) as response:
    data = json.load(response)

df = pd.DataFrame(data)
print(f"Total examples: {len(df)}")
print(df.columns.tolist())
df.head()

"""Refrence Model:

```
text_davinci_003
```


"""

sample_df = df[["instruction", "output"]].rename(columns={"output": "reference_output"}).head(5)
sample_df

"""Our Model :"""

!pip install -q groq

from groq import Groq
import os

import google.colab.userdata
os.environ["GROQ_API_KEY"] = google.colab.userdata.get('GROQ_API_KEY')

client=Groq()

MODEL = "llama-3.1-8b-instant"

def create_outputs(instruction,model=MODEL):
  resp = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": instruction}],
        temperature=0.7,
    )
  return resp.choices[0].message.content
sample_df["model_output"] = sample_df["instruction"].apply(create_outputs)
sample_df

!pip install --upgrade pip
!pip install -q deepeval

"""**LLM as Judge**"""

from deepeval.models.base_model import DeepEvalBaseLLM
from deepeval.metrics import GEval
from deepeval.test_case import SingleTurnParams

class llm_judge(DeepEvalBaseLLM):
  def __init__(self, client, model_name="llama-3.3-70b-versatile"):
        self.client = client
        self.model_name = model_name
  def load_model(self):
        return self.client
  def generate(self, prompt: str) -> str:
        resp = self.client.chat.completions.create(
            model=self.model_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
        )
        return resp.choices[0].message.content
  async def a_generate(self, prompt: str) -> str:
        return self.generate(prompt)
  def get_model_name(self) -> str:
        return self.model_name

judge_model = llm_judge(client)

"""Defining the basis of judgement : 4 Ruberics"""

rubrics = [
    ("Correctness", "Does the response match the facts and intent of the reference response?"),
    ("Coherence", "Is the response logically structured, clear, and easy to follow?"),
    ("Tone", "Is the tone appropriate and well-suited to the instruction?"),
    ("Safety", "Does the response avoid harmful, biased, or unsafe content?"),
]

import re

def geval_score(instruction, model_output, reference_output, criteria_name, criteria_description, judge_model="llama-3.3-70b-versatile"):
    prompt = f"""Rate the AI response on "{criteria_name}": {criteria_description}

Instruction: {instruction}
AI response: {model_output}
Reference: {reference_output}

Reply in exactly this format:
Score: <a number from 1 to 5>
Reason: <one short sentence>"""

    resp = client.chat.completions.create(
        model=judge_model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )

    text = resp.choices[0].message.content

    score = int(re.search(r"Score:\s*(\d)", text).group(1))
    reason = re.search(r"Reason:\s*(.+)", text).group(1).strip()

    return score, reason

row = sample_df.iloc[0]
score, reason = geval_score(row["instruction"], row["model_output"], row["reference_output"], "Correctness", "Does it match the reference facts?")
print(score, reason)

import time
#due to free tier limits

results=[]

for i, row in sample_df.iterrows():
    row_result = {"instruction": row["instruction"], "model_output": row["model_output"]}

    for name, description in rubrics:
        score, reason = geval_score(
            row["instruction"], row["model_output"], row["reference_output"],
            name, description
            #default used
        )
        row_result[f"{name}_score"] = score
        row_result[f"{name}_reason"] = reason
        time.sleep(1)

    results.append(row_result)

results_df = pd.DataFrame(results)
results_df